name: Update Website

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the full history, to build attribution.json
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: yarn

      - uses: microsoft/playwright-github-action@v1

      # Builds the modules, and boostraps the other modules
      - name: Build website
        run: |
          yarn install
          yarn bootstrap
          yarn build
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Builds the site
      - name: Makes the site
        run: |
          yarn build-site
          cp -r packages/lingua-franca/public site
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Deploy to lf-lang.github.io
      - name: Deploy + Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: "gh-pages"
          PUBLISH_DIR: ./site
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     action: "upload"
      #     app_location: "site"
      #     skip_app_build: true

      # Update the site stats
      # - run: node packages/lingua-franca/scripts/updateAppInsightsGitHubIssue.js
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
      #     APP_INSIGHTS_API_KEY: ${{ secrets.APP_INSIGHTS_API_KEY }}
      #     APP_INSIGHTS_ID: ${{ secrets.APP_INSIGHTS_ID }}
